export const INSTRUMENT_BASS_ELECTRIC = {
  "A#1": "bass-electric/As1.mp3",
  "A#2": "bass-electric/As2.mp3",
  "A#3": "bass-electric/As3.mp3",
  "A#4": "bass-electric/As4.mp3",
  "C#1": "bass-electric/Cs1.mp3",
  "C#2": "bass-electric/Cs2.mp3",
  "C#3": "bass-electric/Cs3.mp3",
  "C#4": "bass-electric/Cs4.mp3",
  "C#5": "bass-electric/Cs5.mp3",
  "E1": "bass-electric/E1.mp3",
  "E2": "bass-electric/E2.mp3",
  "E3": "bass-electric/E3.mp3",
  "E4": "bass-electric/E4.mp3",
  "G1": "bass-electric/G1.mp3",
  "G2": "bass-electric/G2.mp3",
  "G3": "bass-electric/G3.mp3",
  "G4": "bass-electric/G4.mp3",
};
