export const INSTRUMENT_GUITAR_ELECTRIC = {
  "A2": "guitar-electric/A2.mp3",
  "A3": "guitar-electric/A3.mp3",
  "A4": "guitar-electric/A4.mp3",
  "A5": "guitar-electric/A5.mp3",
  "C3": "guitar-electric/C3.mp3",
  "C4": "guitar-electric/C4.mp3",
  "C5": "guitar-electric/C5.mp3",
  "C6": "guitar-electric/C6.mp3",
  "C#2": "guitar-electric/Cs2.mp3",
  "D#3": "guitar-electric/Ds3.mp3",
  "D#4": "guitar-electric/Ds4.mp3",
  "D#5": "guitar-electric/Ds5.mp3",
  "E2": "guitar-electric/E2.mp3",
  "F#2": "guitar-electric/Fs2.mp3",
  "F#3": "guitar-electric/Fs3.mp3",
  "F#4": "guitar-electric/Fs4.mp3",
  "F#5": "guitar-electric/Fs5.mp3",
};
