export const INSTRUMENT_PIANO_ACOUSTIC = {
  "A2": "piano-acoustic/A2.mp3",
  "A3": "piano-acoustic/A3.mp3",
  "A4": "piano-acoustic/A4.mp3",
  "A5": "piano-acoustic/A5.mp3",
  "A6": "piano-acoustic/A6.mp3",
  "C2": "piano-acoustic/C2.mp3",
  "C3": "piano-acoustic/C3.mp3",
  "C4": "piano-acoustic/C4.mp3",
  "C5": "piano-acoustic/C5.mp3",
  "C6": "piano-acoustic/C6.mp3",
  "D#2": "piano-acoustic/Ds2.mp3",
  "D#3": "piano-acoustic/Ds3.mp3",
  "D#4": "piano-acoustic/Ds4.mp3",
  "D#5": "piano-acoustic/Ds5.mp3",
  "D#6": "piano-acoustic/Ds6.mp3",
  "F#2": "piano-acoustic/Fs2.mp3",
  "F#3": "piano-acoustic/Fs3.mp3",
  "F#4": "piano-acoustic/Fs4.mp3",
  "F#5": "piano-acoustic/Fs5.mp3",
  "F#6": "piano-acoustic/Fs6.mp3",
};
