export const INSTRUMENT_PIANO_UPRIGHT = {
  "A2": "piano-upright/A2.mp3",
  "A3": "piano-upright/A3.mp3",
  "A4": "piano-upright/A4.mp3",
  "A5": "piano-upright/A5.mp3",
  "A6": "piano-upright/A6.mp3",
  "C2": "piano-upright/C2.mp3",
  "C3": "piano-upright/C3.mp3",
  "C4": "piano-upright/C4.mp3",
  "C5": "piano-upright/C5.mp3",
  "C6": "piano-upright/C6.mp3",
  "D#2": "piano-upright/Ds2.mp3",
  "D#3": "piano-upright/Ds3.mp3",
  "D#4": "piano-upright/Ds4.mp3",
  "D#5": "piano-upright/Ds5.mp3",
  "D#6": "piano-upright/Ds6.mp3",
  "F#2": "piano-upright/Fs2.mp3",
  "F#3": "piano-upright/Fs3.mp3",
  "F#4": "piano-upright/Fs4.mp3",
  "F#5": "piano-upright/Fs5.mp3",
  "F#6": "piano-upright/Fs6.mp3",
};
