import type Keymap from "./type";

const keyToNote = new Map<string, string>()
  .set("1", "C2")
  .set("2", "D2")
  .set("3", "E2")
  .set("4", "F2")
  .set("5", "G2")
  .set("6", "A2")
  .set("7", "B2")
  .set("8", "C3")
  .set("9", "D3")
  .set("0", "E3")
  .set("q", "F3")
  .set("w", "G3")
  .set("e", "A3")
  .set("r", "B3")
  .set("t", "C4")
  .set("y", "D4")
  .set("u", "E4")
  .set("i", "F4")
  .set("o", "G4")
  .set("p", "A4")
  .set("a", "B4")
  .set("s", "C5")
  .set("d", "D5")
  .set("f", "E5")
  .set("g", "F5")
  .set("h", "G5")
  .set("j", "A5")
  .set("k", "B5")
  .set("l", "C6")
  .set("z", "D6")
  .set("x", "E6")
  .set("c", "F6")
  .set("v", "G6")
  .set("b", "A6")
  .set("n", "B6")
  .set("m", "C7")
  .set("!", "C#2")
  .set("@", "D#2")
  .set("$", "F#2")
  .set("%", "G#2")
  .set("^", "A#2")
  .set("*", "C#3")
  .set("(", "D#3")
  .set("Q", "F#3")
  .set("W", "G#3")
  .set("E", "A#3")
  .set("T", "C#4")
  .set("Y", "D#4")
  .set("I", "F#4")
  .set("O", "G#4")
  .set("P", "A#4")
  .set("S", "C#5")
  .set("D", "D#5")
  .set("G", "F#5")
  .set("H", "G#5")
  .set("J", "A#5")
  .set("L", "C#6")
  .set("Z", "D#6")
  .set("C", "F#6")
  .set("V", "G#6")
  .set("B", "A#6")

const noteToKey = new Map<string, string>()
  .set("C2", "1")
  .set("D2", "2")
  .set("E2", "3")
  .set("F2", "4")
  .set("G2", "5")
  .set("A2", "6")
  .set("B2", "7")
  .set("C3", "8")
  .set("D3", "9")
  .set("E3", "0")
  .set("F3", "q")
  .set("G3", "w")
  .set("A3", "e")
  .set("B3", "r")
  .set("C4", "t")
  .set("D4", "y")
  .set("E4", "u")
  .set("F4", "i")
  .set("G4", "o")
  .set("A4", "p")
  .set("B4", "a")
  .set("C5", "s")
  .set("D5", "d")
  .set("E5", "f")
  .set("F5", "g")
  .set("G5", "h")
  .set("A5", "j")
  .set("B5", "k")
  .set("C6", "l")
  .set("D6", "z")
  .set("E6", "x")
  .set("F6", "c")
  .set("G6", "v")
  .set("A6", "b")
  .set("B6", "n")
  .set("C7", "m")
  .set("C#2", "!")
  .set("D#2", "@")
  .set("F#2", "$")
  .set("G#2", "%")
  .set("A#2", "^")
  .set("C#3", "*")
  .set("D#3", "(")
  .set("F#3", "Q")
  .set("G#3", "W")
  .set("A#3", "E")
  .set("C#4", "T")
  .set("D#4", "Y")
  .set("F#4", "I")
  .set("G#4", "O")
  .set("A#4", "P")
  .set("C#5", "S")
  .set("D#5", "D")
  .set("F#5", "G")
  .set("G#5", "H")
  .set("A#5", "J")
  .set("C#6", "L")
  .set("D#6", "Z")
  .set("F#6", "C")
  .set("G#6", "V")
  .set("A#6", "B")

const KEYMAP_STANDARD: Keymap = {
  getKey(note: string): string | undefined {
    return noteToKey.get(note);
  },
  getNote(key: string): string | undefined {
    return keyToNote.get(key);
  }
}


export default KEYMAP_STANDARD;
