import type Keymap from "./type";

const keyToNote = new Map<string, string>()
  .set("1", "C2")
  .set("2", "D2")
  .set("3", "E2")
  .set("4", "F2")
  .set("5", "G2")
  .set("q", "A2")
  .set("w", "B2")
  .set("a", "C3")
  .set("s", "D3")
  .set("d", "E3")
  .set("f", "F3")
  .set("c", "G3")
  .set("v", "A3")
  .set("b", "B3")
  .set("g", "C4")
  .set("h", "D4")
  .set("j", "E4")
  .set("k", "F4")
  .set("l", "G4")
  .set("n", "A4")
  .set("m", "B4")
  .set("e", "C5")
  .set("r", "D5")
  .set("t", "E5")
  .set("y", "F5")
  .set("u", "G5")
  .set("i", "A5")
  .set("o", "B5")
  .set("6", "C6")
  .set("7", "D6")
  .set("8", "E6")
  .set("9", "F6")
  .set("0", "G6")
  .set("z", "A6")
  .set("x", "B6")
  .set("!", "C#2")
  .set("@", "D#2")
  .set("$", "F#2")
  .set("%", "G#2")
  .set("Q", "A#2")
  .set("A", "C#3")
  .set("S", "D#3")
  .set("F", "F#3")
  .set("C", "G#3")
  .set("V", "A#3")
  .set("G", "C#4")
  .set("H", "D#4")
  .set("K", "F#4")
  .set("L", "G#4")
  .set("N", "A#4")
  .set("E", "C#5")
  .set("R", "D#5")
  .set("Y", "F#5")
  .set("U", "G#5")
  .set("I", "A#5")
  .set("^", "C#6")
  .set("&", "D#6")
  .set("(", "F#6")
  .set(")", "G#6")
  .set("Z", "A#6");

const noteToKey = new Map<string, string>()
  .set("C2", "1")
  .set("D2", "2")
  .set("E2", "3")
  .set("F2", "4")
  .set("G2", "5")
  .set("A2", "q")
  .set("B2", "w")
  .set("C3", "a")
  .set("D3", "s")
  .set("E3", "d")
  .set("F3", "f")
  .set("G3", "c")
  .set("A3", "v")
  .set("B3", "b")
  .set("C4", "g")
  .set("D4", "h")
  .set("E4", "j")
  .set("F4", "k")
  .set("G4", "l")
  .set("A4", "n")
  .set("B4", "m")
  .set("C5", "e")
  .set("D5", "r")
  .set("E5", "t")
  .set("F5", "y")
  .set("G5", "u")
  .set("A5", "i")
  .set("B5", "o")
  .set("C6", "6")
  .set("D6", "7")
  .set("E6", "8")
  .set("F6", "9")
  .set("G6", "0")
  .set("A6", "z")
  .set("B6", "x")
  .set("C#2", "!")
  .set("D#2", "@")
  .set("F#2", "$")
  .set("G#2", "%")
  .set("A#2", "Q")
  .set("C#3", "A")
  .set("D#3", "S")
  .set("F#3", "F")
  .set("G#3", "C")
  .set("A#3", "V")
  .set("C#4", "G")
  .set("D#4", "H")
  .set("F#4", "K")
  .set("G#4", "L")
  .set("A#4", "N")
  .set("C#5", "E")
  .set("D#5", "R")
  .set("F#5", "Y")
  .set("G#5", "U")
  .set("A#5", "I")
  .set("C#6", "^")
  .set("D#6", "&")
  .set("F#6", "(")
  .set("G#6", ")")
  .set("A#6", "Z");

const KEYMAP_STANDARD: Keymap = {
  getKey(note: string): string | undefined {
    return noteToKey.get(note);
  },
  getNote(key: string): string | undefined {
    return keyToNote.get(key);
  }
}

export default KEYMAP_STANDARD;
